[package]
name = "tile_world_rust"
version = "0.1.0"
authors = ["Jos Dehaes <jos.dehaes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = "0.2.2"
rand = "0.8.3"