[package]
name = "tileworld"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
log = "0.4"
priority-queue = "1.2"
piston = "0.55"
rusttype = "0.9.2"
piston2d-graphics = "0.44.0"
pistoncore-glutin_window = "0.72.0"
piston2d-opengl_graphics = "0.84.0"
paste = "1.0"
