[package]
name = "tile_world_rust"
version = "0.1.0"
authors = ["Jos Dehaes <jos.dehaes@gmail.com>"]
edition = "2018"

[[bin]]
name = "tile_world_rust"
path = "src/main.rs"

[dependencies]
getrandom = "0.2.2"
rand = "0.8.3"
glib = "^0"
pangocairo = "^0"
cairo-rs = { version = "^0", features = ["png"] }

[dependencies.gtk]
version = "0.14.0"
features = ["v3_24"]

[dependencies.gio]
version = "0.14.6"
