[package]
name = "tileworld"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = "0.14.0"
log = "0.4"
paste = "1.0"
piston = "1.0"
piston2d-graphics = "0.45"
piston2d-opengl_graphics = "0.89"
pistoncore-glutin_window = "0.72"
priority-queue = "2.5"
rand = "0.9"
rusttype = "0.9.2"
